run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - whitespace
    - bodyclose
    - durationcheck
    - gosec
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gosec:
    excludes:
      - G107
      - G108
      - G110
      - G115
      - G204
      - G301
      - G302
      - G304
      - G306
      - G401
      - G402
      - G404

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - rowserrcheck
        - sqlclosecheck
        - durationcheck
        - thelper
        - unused
    - path: pkg/logger/logger.go
      linters:
        - errcheck