run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - prealloc
    - unconvert
    - whitespace
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goprintffuncname
    - gosec
    - lll
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unparam
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gochecknoglobals
        - gocyclo
        - lll
    - path: pkg/logger/logger.go
      linters:
        - gochecknoglobals